### ISSUE TITLE
ES38 alternative?

### ISSUE THREAD

**Issue by Leepee** [semenmiroshnichenko/ESP32Focuser-hardware#1]
Awesome project, I really want to build one! But I have a snag. We did a silly thing in the UK and Brexit happened. Since then, Aliexpress is near enough useless :( 

I can source all the parts aside from the rotary encoder. Is there a reasonable alternative you can recommend?

Thanks

**Comment by simonachmueller** [comment]
Hi @Leepee, nice to hear your feedback. I bought my first encoder on amazon, is that an option for you? Back then (about 2 years ago) I found "WISAMIC 600p Incremental Rotary Encoder" for a reasonable price, check it out. 

Using a mechanical encoder is also possible, but I highly recommend using an optical one as it has a very good resolution.

**Comment by simonachmueller** [comment]
I hope I answered your question so I'll close the issue. If not, just reopen it.
